### ISSUE TITLE
Could not read folder: test/intl...

### ISSUE THREAD

**Issue by nojaf** [rescript-lang/rewatch#131] opened 2024-09-06 12:37 UTC
Not sure if I should still report issues here, but I keep seeing the log message `Could not read folder: test/intl...`.

Why is it trying to read that folder?

**Comment by hellos3b** [comment] 2024-10-09 04:20
I see this as well

**Comment by adnelson** [comment] 2024-10-15 18:40
Not sure if it's the same thing but I was getting similar issues and it was caused by a dead symlink in my folder structure, which caused one of the `fs::metadata` calls inside of `rewatch` to fail. I have a pr #136 that fixes that.

**Comment by rolandpeelen** [comment] 2024-11-15 22:19
Fixed in https://github.com/rescript-lang/rewatch/pull/140 👌

**Closed by rolandpeelen** 2024-11-15 22:19 UTC
